[2023-01-30T12:40:08.402+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: flights_data.dbt_step manual__2023-01-30T12:40:05.448534+00:00 [queued]>
[2023-01-30T12:40:08.407+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: flights_data.dbt_step manual__2023-01-30T12:40:05.448534+00:00 [queued]>
[2023-01-30T12:40:08.408+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T12:40:08.408+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-30T12:40:08.409+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T12:40:08.417+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): dbt_step> on 2023-01-30 12:40:05.448534+00:00
[2023-01-30T12:40:08.422+0000] {standard_task_runner.py:55} INFO - Started process 17139 to run task
[2023-01-30T12:40:08.425+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'flights_data', 'dbt_step', 'manual__2023-01-30T12:40:05.448534+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/tmp/tmpvw1v5mjk']
[2023-01-30T12:40:08.426+0000] {standard_task_runner.py:83} INFO - Job 58: Subtask dbt_step
[2023-01-30T12:40:08.476+0000] {task_command.py:388} INFO - Running <TaskInstance: flights_data.dbt_step manual__2023-01-30T12:40:05.448534+00:00 [running]> on host f9ad67e64070
[2023-01-30T12:40:08.522+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=flights_data
AIRFLOW_CTX_TASK_ID=dbt_step
AIRFLOW_CTX_EXECUTION_DATE=2023-01-30T12:40:05.448534+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-30T12:40:05.448534+00:00
[2023-01-30T12:40:08.525+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-01-30T12:40:08.526+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd ../ && cd ../ && ls"']
[2023-01-30T12:40:08.539+0000] {subprocess.py:86} INFO - Output:
[2023-01-30T12:40:08.541+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: unexpected EOF while looking for matching `"'
[2023-01-30T12:40:08.542+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2023-01-30T12:40:08.542+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-01-30T12:40:08.553+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-01-30T12:40:08.555+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=flights_data, task_id=dbt_step, execution_date=20230130T124005, start_date=20230130T124008, end_date=20230130T124008
[2023-01-30T12:40:08.563+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 58 for task dbt_step (Bash command failed. The command returned a non-zero exit code 2.; 17139)
[2023-01-30T12:40:08.599+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-30T12:40:08.613+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
