[2023-01-30T12:34:45.524+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: flights_data.dbt_step manual__2023-01-30T12:34:42.325272+00:00 [queued]>
[2023-01-30T12:34:45.530+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: flights_data.dbt_step manual__2023-01-30T12:34:42.325272+00:00 [queued]>
[2023-01-30T12:34:45.531+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T12:34:45.532+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-30T12:34:45.532+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T12:34:45.541+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): dbt_step> on 2023-01-30 12:34:42.325272+00:00
[2023-01-30T12:34:45.546+0000] {standard_task_runner.py:55} INFO - Started process 16753 to run task
[2023-01-30T12:34:45.550+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'flights_data', 'dbt_step', 'manual__2023-01-30T12:34:42.325272+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/tmp/tmpfxfq6bx3']
[2023-01-30T12:34:45.551+0000] {standard_task_runner.py:83} INFO - Job 48: Subtask dbt_step
[2023-01-30T12:34:45.608+0000] {task_command.py:388} INFO - Running <TaskInstance: flights_data.dbt_step manual__2023-01-30T12:34:42.325272+00:00 [running]> on host f9ad67e64070
[2023-01-30T12:34:45.655+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=flights_data
AIRFLOW_CTX_TASK_ID=dbt_step
AIRFLOW_CTX_EXECUTION_DATE=2023-01-30T12:34:42.325272+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-30T12:34:42.325272+00:00
[2023-01-30T12:34:45.658+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-01-30T12:34:45.659+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /transform && echo "$PWD"']
[2023-01-30T12:34:45.670+0000] {subprocess.py:86} INFO - Output:
[2023-01-30T12:34:45.672+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /transform: No such file or directory
[2023-01-30T12:34:45.673+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-01-30T12:34:45.683+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-01-30T12:34:45.685+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=flights_data, task_id=dbt_step, execution_date=20230130T123442, start_date=20230130T123445, end_date=20230130T123445
[2023-01-30T12:34:45.694+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 48 for task dbt_step (Bash command failed. The command returned a non-zero exit code 1.; 16753)
[2023-01-30T12:34:45.723+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-30T12:34:45.737+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
