[2023-01-30T16:41:45.292+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: flights_data.dbt_step scheduled__2023-01-29T00:00:00+00:00 [queued]>
[2023-01-30T16:41:45.298+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: flights_data.dbt_step scheduled__2023-01-29T00:00:00+00:00 [queued]>
[2023-01-30T16:41:45.299+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T16:41:45.299+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-30T16:41:45.300+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T16:41:45.309+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): dbt_step> on 2023-01-29 00:00:00+00:00
[2023-01-30T16:41:45.315+0000] {standard_task_runner.py:55} INFO - Started process 537 to run task
[2023-01-30T16:41:45.320+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'flights_data', 'dbt_step', 'scheduled__2023-01-29T00:00:00+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/tmp/tmpea65es_f']
[2023-01-30T16:41:45.321+0000] {standard_task_runner.py:83} INFO - Job 96: Subtask dbt_step
[2023-01-30T16:41:45.373+0000] {task_command.py:388} INFO - Running <TaskInstance: flights_data.dbt_step scheduled__2023-01-29T00:00:00+00:00 [running]> on host 4d49ce0454d7
[2023-01-30T16:41:45.452+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=flights_data
AIRFLOW_CTX_TASK_ID=dbt_step
AIRFLOW_CTX_EXECUTION_DATE=2023-01-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-29T00:00:00+00:00
[2023-01-30T16:41:45.488+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-01-30T16:41:45.506+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd dbt && ls']
[2023-01-30T16:41:45.532+0000] {subprocess.py:86} INFO - Output:
[2023-01-30T16:41:45.533+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: dbt: No such file or directory
[2023-01-30T16:41:45.534+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-01-30T16:41:45.545+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-01-30T16:41:45.548+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=flights_data, task_id=dbt_step, execution_date=20230129T000000, start_date=20230130T164145, end_date=20230130T164145
[2023-01-30T16:41:45.559+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 96 for task dbt_step (Bash command failed. The command returned a non-zero exit code 1.; 537)
[2023-01-30T16:41:45.611+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-30T16:41:45.625+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
