[2023-01-31T14:31:05.110+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: flights_data.dbt_step manual__2023-01-31T14:31:02.548032+00:00 [queued]>
[2023-01-31T14:31:05.117+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: flights_data.dbt_step manual__2023-01-31T14:31:02.548032+00:00 [queued]>
[2023-01-31T14:31:05.118+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-31T14:31:05.118+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-31T14:31:05.118+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-31T14:31:05.126+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): dbt_step> on 2023-01-31 14:31:02.548032+00:00
[2023-01-31T14:31:05.131+0000] {standard_task_runner.py:55} INFO - Started process 734 to run task
[2023-01-31T14:31:05.135+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'flights_data', 'dbt_step', 'manual__2023-01-31T14:31:02.548032+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/flights_dag.py', '--cfg-path', '/tmp/tmpoya7mfap']
[2023-01-31T14:31:05.135+0000] {standard_task_runner.py:83} INFO - Job 117: Subtask dbt_step
[2023-01-31T14:31:05.192+0000] {task_command.py:388} INFO - Running <TaskInstance: flights_data.dbt_step manual__2023-01-31T14:31:02.548032+00:00 [running]> on host 4d49ce0454d7
[2023-01-31T14:31:05.244+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=flights_data
AIRFLOW_CTX_TASK_ID=dbt_step
AIRFLOW_CTX_EXECUTION_DATE=2023-01-31T14:31:02.548032+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-31T14:31:02.548032+00:00
[2023-01-31T14:31:05.246+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-01-31T14:31:05.247+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt && dbt run']
[2023-01-31T14:31:05.260+0000] {subprocess.py:86} INFO - Output:
[2023-01-31T14:31:05.262+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2023-01-31T14:31:05.263+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-01-31T14:31:05.273+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-01-31T14:31:05.276+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=flights_data, task_id=dbt_step, execution_date=20230131T143102, start_date=20230131T143105, end_date=20230131T143105
[2023-01-31T14:31:05.285+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 117 for task dbt_step (Bash command failed. The command returned a non-zero exit code 127.; 734)
[2023-01-31T14:31:05.307+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-31T14:31:05.323+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
