[2023-01-30T12:31:45.803+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: flights_data.dbt_step manual__2023-01-30T12:31:42.498274+00:00 [queued]>
[2023-01-30T12:31:45.808+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: flights_data.dbt_step manual__2023-01-30T12:31:42.498274+00:00 [queued]>
[2023-01-30T12:31:45.809+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T12:31:45.809+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-30T12:31:45.810+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T12:31:45.817+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): dbt_step> on 2023-01-30 12:31:42.498274+00:00
[2023-01-30T12:31:45.823+0000] {standard_task_runner.py:55} INFO - Started process 16552 to run task
[2023-01-30T12:31:45.826+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'flights_data', 'dbt_step', 'manual__2023-01-30T12:31:42.498274+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/tmp/tmpd1v1q93b']
[2023-01-30T12:31:45.827+0000] {standard_task_runner.py:83} INFO - Job 45: Subtask dbt_step
[2023-01-30T12:31:45.879+0000] {task_command.py:388} INFO - Running <TaskInstance: flights_data.dbt_step manual__2023-01-30T12:31:42.498274+00:00 [running]> on host f9ad67e64070
[2023-01-30T12:31:45.925+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=flights_data
AIRFLOW_CTX_TASK_ID=dbt_step
AIRFLOW_CTX_EXECUTION_DATE=2023-01-30T12:31:42.498274+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-30T12:31:42.498274+00:00
[2023-01-30T12:31:45.928+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-01-30T12:31:45.929+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd ~/transform && echo "$PWD"']
[2023-01-30T12:31:45.940+0000] {subprocess.py:86} INFO - Output:
[2023-01-30T12:31:45.942+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /home/***/transform: No such file or directory
[2023-01-30T12:31:45.943+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-01-30T12:31:45.953+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-01-30T12:31:45.956+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=flights_data, task_id=dbt_step, execution_date=20230130T123142, start_date=20230130T123145, end_date=20230130T123145
[2023-01-30T12:31:45.965+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 45 for task dbt_step (Bash command failed. The command returned a non-zero exit code 1.; 16552)
[2023-01-30T12:31:45.999+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-30T12:31:46.013+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
